# Generated by Django 3.2.3 on 2021-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_create_walk_stop_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='location_text',
            field=models.CharField(max_length=256),
        ),
    ]
