# Generated by Django 3.2.3 on 2021-05-27 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_post_reply_to'),
        ('walks', '0003_auto_20210526_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='comment_thread',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forums.thread'),
        ),
    ]
