# Generated by Django 3.2.3 on 2021-05-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='post_count',
            field=models.IntegerField(default=0),
        ),
    ]
